### COSTS LIST
GET http://localhost:3000/costs


### CREATE COSTS
POST http://localhost:3000/costs
content-type: application/json

{
  "id": 2,
  "idUsuario": 2,
  "idReceita": 2,
  "totalMaterialCost": 60.0,
  "totalTimeValue": 3.0,
  "totalCost": 63.0
}

### UPDATE COSTS
PUT http://localhost:3000/costs/1
content-type: application/json

{
  "id": 2,
  "idUsuario": 2,
  "idReceita": 2,
  "totalMaterialCost": 10.0,
  "totalTimeValue": 5.0,
  "totalCost": 15.0
}


### GET COSTS
GET http://localhost:3000/costs/1

### DELETE COSTS
DELETE http://localhost:3000/costs/1
