### GET RECIPE LIST
GET http://localhost:3000/recipe


### CREATE RECIPE
POST http://localhost:3000/recipe
content-type: application/json

{
  "name": "pudim",
  "hourValue": 0,
  "appliesDefaultValue": true,
  "comments": "",
  "color": "#98FB98",
  "id": 9,
  "preparationTime": 0,
  "startDate": "2023-11-21T12:34:56.789Z",
  "isConcluded": false
}

### UPDATE RECIPE
PUT http://localhost:3000/recipe/1
content-type: application/json

{
  "id": 1,
  "name": "torta de manteiga escocesa",
  "hourValue": 3.0,
  "appliesDefaultValue": false,
  "comments": "Testando a receita com flor de sal",
  "color":"#176B87",
  "preparationTime": 0.0,
  "startDate": "2023-11-21T12:34:56.789Z",
  "isConcluded": false
}


### GET RECIPE
GET http://localhost:3000/recipe/1

### DELETE RECIPE
DELETE http://localhost:3000/recipe/4
