#@TOKEN=TOKEN_KEY
#### LOGIN
#POST https://cooklator-backend.onrender.com/login
#content-type: application/json
#
#{
#  "email": "klebersouza@pucminas.br",
#  "password":"pucminas"
#}


### USER LIST
GET https://cooklator-backend.onrender.com/user
#GET https://cooklator-backend.onrender.com/660/user
#Authorization: Bearer {{TOKEN}}

### CREATE USER
#POST https://cooklator-backend.onrender.com/660/user
POST https://cooklator-backend.onrender.com/user
content-type: application/json
#Authorization: Bearer {{TOKEN}}

{
  "id": 2,
  "name": "Juliana Teste",
  "email": "juteste@tste.com",
  "password": "senha123",
  "hourValue": 5.0
}

### UPDATE USER
PUT https://cooklator-backend.onrender.com/user/1
#PUT https://cooklator-backend.onrender.com/660/user/1
content-type: application/json
#Authorization: Bearer {{TOKEN}}

{
  "id": 1,
  "name": "Juliana",
  "email": "ju@tste.com",
  "password": "senha",
  "hourValue": 5.0
}


### GET USER
GET https://cooklator-backend.onrender.com/user/1
#GET https://cooklator-backend.onrender.com/660/user/1
#Authorization: Bearer {{TOKEN}}

### DELETE USER
DELETE https://cooklator-backend.onrender.com/user/1
#DELETE https://cooklator-backend.onrender.com/660/user/1
#Authorization: Bearer {{TOKEN}}
